[build]
builder = "nixpacks"
buildCommand = "(cd storefront || true) && (npm install || npm ci) && npm run build"

[deploy]
startCommand = "(cd storefront || true) && npm run start"
restartPolicyType = "always"
